# OAuth2 Configuration
oauth.authUrl=https://www.dropbox.com
oauth.clientId=ENTER_PROVIDE_CLINET_ID
oauth.clientSecret=ENTER_PROVIDE_CLINET_SECRET
oauth.refreshToken=ENTER_PROVIDE_REFRESH_TOKEN

# API URL for Data Fetch
oauth.apiUrl=https://api.dropboxapi.com
